[package]
edition = "2018"
name = "snork"
version = "0.1.1"
authors = ["Lars Wrenger <lars@wrenger.net>", "Julian Krohne <krohnejulian@yahoo.de>", "Julian Gercke <julian.gercke@gmx.de>"]
description = "High performant battlesnake agents written in rust"
license = "MIT"
resolver = "2"
default-run = "server"

[dependencies]
actix-rt = "2.2"
actix-web = "3.3"
chashmap = "2.2"
rand = {version = "0.8", features = ["small_rng"]}
serde = "1.0"
serde_json = "1.0"
structopt = "0.3"
threadpool = "1.8"
owo-colors = "3.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false
test = false

[[bin]]
name = "server"

[[bin]]
name = "move"

[[bin]]
name = "simulate"

[profile.release]
lto = true
opt-level = 3
