[package]
edition = "2018"
name = "snork"
version = "0.1.1"
authors = ["Lars Wrenger <lars@wrenger.net>", "Julian Krohne <krohnejulian@yahoo.de>", "Julian Gercke <julian.gercke@gmx.de>"]
description = "High performant battlesnake agents written in rust"
default-run = "snork"
license = "MIT"

[dependencies]
snork_core = {version = "0.1.0", path = "snork_core"}
actix-rt = "2.2"
actix-web = "3.3"
chashmap = "2.2"
rand = {version = "0.8", features = ["small_rng"]}
serde = "1.0"
serde_json = "1.0"
structopt = "0.3"
threadpool = "1.8"

[[bin]]
name = "move"
path = "src/move.rs"
test = false

[[bin]]
name = "simulate"
path = "src/simulate.rs"
test = false

[workspace]
members = ["snork_core"]

[profile.release]
lto = true
opt-level = 3
